title: "Habsa DEME"
email: "habsademe10@gmail.com"
description: "Portfolio - Développeuse Web & Data Analyst"
baseurl: ""
url: "https://habsa-dev.github.io"

social:
  github: "https://github.com/habsa-dev"
  email: "mailto:habsademe10@gmail.com"
  linkedin: "https://www.linkedin.com/in/habsa-deme-4275272a5/"

